<h1>
    <a href="/">Пользователи</a>
    <span class="glyphicon glyphicon-play btn btn-sm grey breadcrumbsIcon"></span>
    <?php if ($this->name) { echo $this->name; } else { ?>Добавить пользователя <?php } ?>
</h1>

<?php if ($this->err) { ?>
    <div class="alert alert-danger">
        <?php echo $this->err;?>
    </div>
<?php } ?>
<?php if ($this->save) { ?>
    <div class="alert alert-success">
        Изменения успешно сохранены.
    </div>
<?php } ?>

<form id="categoriesForm" enctype="application/x-www-form-urlencoded" method="post" action="">
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'name')?>">
        <div class="grey ml10">
            Имя <span class="red">*</span>
        </div>
        <?=$this->form->getElement('name') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'name')?></span>
    </div>
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'industry')?>">
        <div class="grey ml10">
            Индустрия <span class="red">*</span>
        </div>
        <?=$this->form->getElement('industry') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'industry')?></span>
    </div>
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'goal')?>">
        <div class="grey ml10">
            Цель
        </div>
        <?=$this->form->getElement('goal') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'goal')?></span>
    </div>
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'city')?>">
        <div class="grey ml10">
            Город <span class="red">*</span>
        </div>
        <?=$this->form->getElement('city') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'city')?></span>
    </div>
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'is_free')?>">
        <div class="grey ml10">
            Свободен <span class="red">*</span>
        </div>
        <?=$this->form->getElement('is_free') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'is_free')?></span>
    </div>
    <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'offset')?>">
        <div class="grey ml10">
            Таймзона <span class="red">*</span>
        </div>
        <?=$this->form->getElement('offset') ?>
        <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'offset')?></span>
    </div>


    <div class="bottomSaveBox">
        <div class="crudButtons">
            <?=$this->form->getElement('ok') ?>
            <span class="helpButtons"><a class="btn btn-lg btn-default saveBoxButton" href="/">Отмена</a></span>
            <?php if ($this->name) { ?><span class="helpButtons"><a class="btn btn-lg btn-danger pull-right saveBoxButton mr20" href="/delete/id/<?=$this->id?>">Удалить пользователя</a></span><?php } ?>
        </div>
    </div>

</form>