<h1>
    Пользователи
    <a href="/index/edit/" class="btn btn-success btn-lg pull-right" style="margin-top: -7px;">Добавить пользователя</a>
</h1>


<?php if ($this->err) { ?>
    <div class="alert alert-danger">
        <?php echo $this->err;?>
    </div>
<?php } ?>
<?php if ($this->save) { ?>
    <div class="alert alert-success">
        Пользователя добавлено.
    </div>
<?php } ?>

<?php if ($this->users) { ?>
    <table class="table myTable">
        <thead>
        <tr></tr>
        <tr class="active" style="height: 50px;">
            <th style="padding-left: 20px;">Название</th>
            <th>Название города</th>
            <th>Индустрия</th>
            <th>Цель</th>
            <th>Свободен</th>
            <th>Зона</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody class="sortable">
        <?php foreach($this->users as $row) { ?>
            <tr id="<?=$row['id']?>" data-order="<?=$row['order']?>" data-id="<?=$row['id']?>" class="sort">
                <td style="padding-left: 20px;"><?=$row['name']?></td>
                <td><?=$row['city_name']?></td>
                <td><?=$row['industry']?></td>
                <td><?=$row['goal']?></td>
                <td><?php if ($row['free_time']) echo 'On'; else echo 'Off';?></td>
                <td><?=$row['offset']?></td>
                <td>
                    <a class="btn btn-primary btn-sm" href="/calendar/index/id/<?=$row['id']?>">События</span></a>
                    <a class="btn btn-success btn-sm" href="/result/index/id/<?=$row['id']?>">Результат</span></a>
                    <a class="btn btn-default btn-sm" href="/index/edit/id/<?=$row['id']?>"><span class="glyphicon glyphicon-pencil"></span></a>
                    <a class="btn btn-default btn-sm" href="/index/delete/id/<?=$row['id']?>"><span class="glyphicon glyphicon-trash"></span></a>
                </td>
                <td>
                    <div class="grey-palki">
                        <div class="grey-palka"></div>
                        <div class="grey-palka"></div>
                        <div class="grey-palka"></div>
                    </div>
                </td>
            </tr>
        <?php } ?>
        <tr>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
            <td></td>
        </tr>
        </tbody>
    </table>
<?php } else { ?>
    <div class="noItems">
        <div class="noItemsIcon"><span class="glyphicon glyphicon-user"></span></div>
        <div class="noItemsText">Список пользователей пуст</div>
    </div>
<?php } ?>

<div class="addCategoryBox mt80">
    <div class="pull-center"><a href="/index/edit/" class="btn btn-success btn-lg">Добавить пользователя</a></div>
</div>