<?php echo $this->search ?>
<?php if (count($this->items)) { ?>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><strong>#</strong></th>
            <th><strong>From</strong></th>
            <th><strong>To</strong></th>
            <th><strong>Description</strong></th>
            <th><strong>Time create</strong></th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->items as $item) { ?>
            <tr>
                <td><?php echo $item['id'];?></td>
                <td><?=$item['name1'];?> <?=$item['lastname1'];?> (<?=$item['email1'];?>)</td>
                <td><?=$item['name2'];?> <?=$item['lastname2'];?> (<?=$item['email2'];?>)</td>
                <td><?php echo $item['dscr'];?></td>
                <td><?php echo $item['create_at'];?></td>
            </tr>
        <?php } ?>
    </table>
    <?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>
<?php } ?>