<h1>
    <a href="/run/">Запуск</a>
</h1>

<?php if ($this->err) { ?>
    <div class="alert alert-danger">
        <?php echo $this->err;?>
    </div>
<?php } ?>

<?php
    if ($this->data) {
?>




        <div class="panel-group" id="accordion">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                            Parsed
                        </a>
                    </h4>
                </div>
                <div id="collapseOne" class="panel-collapse collapse in">
                    <div class="panel-body">
                        <?=$this->data?>
                    </div>
                </div>
            </div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4 class="panel-title">
                        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
                            Unparsed
                        </a>
                    </h4>
                </div>
                <div id="collapseTwo" class="panel-collapse collapse">
                    <div class="panel-body">
                        <?php r($this->dd); ?>
                    </div>
                </div>
            </div>
        </div>

    <?php } else {?>

    <form id="categoriesForm" enctype="application/x-www-form-urlencoded" method="post" action="">
        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'start_time')?>">
            <div class="grey ml10">
                Начало <span class="red">*</span>
            </div>
            <?=$this->form->getElement('start_time') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'start_time')?></span>
        </div>

        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'end_time')?>">
            <div class="grey ml10">
                Конец <span class="red">*</span>
            </div>
            <?=$this->form->getElement('end_time') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'end_time')?></span>
        </div>

        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'industry')?>">
            <div class="grey ml10">
                 Индустрия <span class="red">*</span>
            </div>
            <?=$this->form->getElement('industry') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'industry')?></span>
        </div>

        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'goal')?>">
            <div class="grey ml10">
                Цель <span class="red">*</span>
            </div>
            <?=$this->form->getElement('goal') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'goal')?></span>
        </div>

        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'city')?>">
            <div class="grey ml10">
                Город <span class="red">*</span>
            </div>
            <?=$this->form->getElement('city') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'city')?></span>
        </div>

        <div class="form-group <?=Application_Model_Common::hasErrors($this->form,'offset')?>">
            <div class="grey ml10">
                Зона <span class="red">*</span>
            </div>
            <?=$this->form->getElement('offset') ?>
            <span class="ml10 red"><?=Application_Model_Common::renderErrors($this->form,'offset')?></span>
        </div>


        <div class="bottomSaveBox">
            <div class="crudButtons">
                <?=$this->form->getElement('ok') ?>
            </div>
        </div>

    </form>

<?php } ?>