<?php echo $this->search ?>
<?php if (count($this->items)) { ?>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><strong>#</strong></th>
            <th><strong>URL</strong></th>
            <th><strong>IN</strong></th>
            <th><strong>OUT</strong></th>
            <th><strong>Time</strong></th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->items as $item) { ?>
            <tr>
                <td><?php echo $item['id'];?></td>
                <td><?php echo $item['url'];?></td>
                <td><?php echo $item['data_in'];?></td>
                <td><?php echo $item['data_out'];?></td>
                <td><?php echo $item['time'];?></td>
            </tr>
        <?php } ?>
    </table>
    <?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>
<?php } ?>