<?php echo $this->search ?>
<a href="/admin/logs/delete" class="btn btn-danger del-all">Delete all</a>
<?php if (count($this->items)) { ?>
    <div class="panel-group" id="accordion">
        <?php foreach ($this->items as $item) { ?>
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">
                    <small class="text-muted"><?php echo $item['time'];?></small>
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#<?=$item['id']?>">
                        <strong><?php echo $item['url'];?></strong>
                    </a>
                </h3>
            </div>
            <div id="<?=$item['id']?>" class="panel-collapse collapse">
                <div class="panel-body">
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th class="warning"><strong>DATA IN</strong></th>
                            <th class="danger"><strong>DATA OUT</strong></th>
                        </tr>
                        </thead>
                        <tr>
                            <td class="warning" style="min-width: 500px"><code class="language-json"><?=$item['data_in']?></code></td>
                            <td class="danger" style="min-width: 600px;"><?php echo $item['data_out'];?></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <?php } ?>
    </div>
    <?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>
<?php } ?>

<script src="/js/ace/ace.js" type="text/javascript" charset="utf-8"></script>
<script src="/js/ace/ext-static_highlight.js"></script>

<script>
    highlight();
//    $(".collapse").collapse();

    function highlight() {
        var highlighter = ace.require("ace/ext/static_highlight")
        var dom = ace.require("ace/lib/dom")
        function qsa(sel) {
            return [].slice.call(document.querySelectorAll(sel));
        }

        qsa("code[class]").forEach(function(el) {
            var m = el.className.match(/language-(\w+)|(javascript)/);
            if (!m) return
            var mode = "ace/mode/" + (m[1] || m[2]);
            var theme = "ace/theme/xcode";
            var data = dom.getInnerText(el).trim();

            highlighter.render(data, mode, theme, 1, true, function (highlighted) {
                dom.importCssString(highlighted.css, "ace_highlight");
                el.innerHTML = highlighted.html;
            });
        });


    }
</script>