<?php echo $this->search ?>
<?php if (count($this->items)) { ?>
    <table class="table table-striped table-hover">
        <thead>
        <tr>
            <th><strong>Photo</strong></th>
            <th><strong>Email</strong></th>
            <th><strong>Name</strong></th>
            <th><strong>Last name</strong></th>
            <th><strong>Phone</strong></th>
            <th><strong>City</strong></th>
            <th><strong>Status</strong></th>
            <th></th>
        </tr>
        </thead>
        <?php foreach ($this->items as $item) { ?>
            <tr>
                <td><?php if ($item['photo']) {?><img class="img-thumbnail imgUser" src="<?php echo $this->photoUrl.$item['photo'];?>" alt=""/><?php } ?></td>
                <td><?php echo $item['email'];?></td>
                <td><?php echo $item['name'];?></td>
                <td><?php echo $item['lastname'];?></td>
                <td><?php echo $item['phone'];?></td>
                <td><?php echo $item['city_name'];?></td>
                <td><?php if ($item['status']==0) echo "Active";
                    elseif ($item['status']==1) echo "Blocked";
                    else echo $item['status'];
                    ?></td>
                <td><a class="btn btn-default " href="<?php echo $this->url(array(
                        "module" => "admin",
                        "controller" => "users",
                        "action" => "edit",
                        "id" => $item["id"]), null, true)?>">edit</a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <?php echo $this->paginationControl($this->items, 'Sliding', 'pagination.phtml'); ?>
<?php } ?>